export type Lang = "tr" | "en";
export type RouteChoice = "work" | "careers";

export const content = {
  tr: {
    eyebrow: "İletişim / Fırsatlar", heroTitle: "Nasıl tanışıyoruz?", heroBody: "Bir büyüme hedefi, yeni bir proje veya birlikte üretme ihtimali. Başlangıç noktanızı seçin.", soundOn: "Sesi kapat", soundOff: "Sesi aç",
    workCard: { label: "Bizimle Çalışın", title: "Gerçek Büyüme İçin Bize Ulaşın.", body: "Markanızı büyütmek, yeni bir pazara açılmak, yeni bir ürün veya alt marka lansmanı yapmak ya da dijital bir ürün geliştirmek istiyorsanız hedeflerinizi birlikte somut bir büyüme planına dönüştürelim.", cta: "Markanızı Konuşalım" },
    careersCard: { label: "Ekibimize Katılın", title: "Birlikte neler yapabiliriz?", body: "Uzmanlığınızı tanıyalım. Doğru insan, doğru zaman ve doğru proje fark yaratır.", cta: "Kendinizi Tanıtın" },
    offices: { eyebrow: "Global Varlık", title: "İki ana ofis, beş şehir, tek çalışma standardı.", body: "İstanbul ve New York’taki ana ofislerimiz ile Dubai, Gaziantep ve Paris’teki temsil yapımız; farklı pazarlara yakın, entegre bir çalışma modeli oluşturuyor.", main: "Ana Ofis", representatives: "Temsil Ofisleri", directions: "Yol Tarifi Al", contact: "Doğrudan İletişim" },
    work: { eyebrow: "Bizimle Çalışın", title: "Hedefi Siz Belirleyin, Yolu Biz.", body: "Yeni pazarlara girişten marka ve ürün lansmanlarına, büyüme stratejisinden teknoloji ve operasyon altyapısına kadar hedeflerinizi sürdürülebilir, ölçülebilir ve ölçeklenebilir bir sisteme dönüştürüyoruz.", switch: "Ekibimize katılmak mı istiyorsunuz?", formEyebrow: "Projenizi Anlatın", formTitle: "Bir sonraki büyüme adımını birlikte planlayalım.", formBody: "Yeni bir pazar, ürün lansmanı, alt marka, pazarlama operasyonu, dijital ürün veya yazılım projesi… Hedefinizi ve ihtiyaç duyduğunuz kapsamı paylaşmanız, doğru başlangıç noktasını belirlememiz için yeterli.", submit: "Projenizi Gönderin", success: "Projeniz ekibimize ulaştı. Paylaştığınız bilgileri değerlendirdikten sonra sizinle iletişime geçeceğiz." },
    careers: { eyebrow: "Careers & Opportunities", title: "İlan açmayı beklemeden tanışalım.", body: "Her zaman açık bir pozisyonumuz olmayabilir. Ancak doğru insanlarla tanışmak için yeni bir ilan yayınlamayı beklemiyoruz. Uzmanlığınızı bizimle paylaşın; uygun bir proje doğduğunda sizi hatırlayalım.", switch: "Bir proje mi konuşmak istiyorsunuz?", networkLabel: "Sellf Talent Network", networkTitle: "İyi işler, doğru insanların bir araya gelmesiyle çıkar.", networkBody: "Sellf’in projeleri farklı disiplinlerden uzmanların katkısıyla büyüyor. Freelancer, dönemsel veya proje bazlı çalışıyorsanız sizi, yaklaşımınızı ve ürettiklerinizi tanımak isteriz.", modesTitle: "Projenin ihtiyacına göre bir araya geliyoruz.", modesBody: "Freelance, dönemsel, proje bazlı veya uzun dönemli iş birlikleri kuruyoruz. Bu form aktif bir iş ilanı veya istihdam garantisi değildir; uygun bir ihtiyaç oluştuğunda yeniden konuşabilmek için tanışma alanıdır.", formLabel: "Kendinizi Tanıtın", formTitle: "Neyi iyi yaptığınızı bize gösterin.", formBody: "Uzun bir ön yazıya ihtiyacımız yok. Uzmanlığınızı, yaklaşımınızı ve daha önce ürettiğiniz işleri paylaşmanız yeterli.", submit: "Profilimi Gönder", success: "Profiliniz Talent Network’e eklendi. Uygun bir proje veya fırsat oluştuğunda sizinle iletişime geçeceğiz." },
    fields: { name: "Ad Soyad", email: "E-posta", workEmail: "İş E-postası", phone: "Telefon (isteğe bağlı)", company: "Şirket / Marka", website: "Website (isteğe bağlı)", goal: "Hangi hedef üzerinde çalışmak istiyorsunuz?", brief: "Projenizi, hedeflerinizi ve ihtiyaç duyduğunuz kapsamı kısaca paylaşın.", start: "Ne zaman başlamak istiyorsunuz?", budget: "Yaklaşık bütçe aralığı (isteğe bağlı)", location: "Şehir / Ülke", expertise: "Uzmanlık alanı", portfolio: "Portfolyo / Website", linkedin: "LinkedIn (isteğe bağlı)", model: "Tercih ettiğiniz çalışma modeli", availability: "Uygunluk durumu", intro: "Kısaca kendinizden ve çalışma yaklaşımınızdan bahsedin.", cv: "CV (isteğe bağlı, PDF/DOC/DOCX — en fazla 5 MB)", error: "Bir sorun oluştu. Lütfen tekrar deneyin veya team@sellfmedia.com adresine yazın.", sending: "Gönderiliyor…" }
  },
  en: {
    eyebrow: "Contact / Opportunities", heroTitle: "What brings us together?", heroBody: "A growth ambition, a new project, or the possibility of building something together. Choose where we begin.", soundOn: "Mute sound", soundOff: "Enable sound",
    workCard: { label: "Work With Us", title: "Build Real Growth With Us.", body: "Whether you are growing a brand, entering a new market, launching a product or sub-brand, or building a digital product, we turn your ambition into a concrete growth plan.", cta: "Let’s Talk About Your Brand" },
    careersCard: { label: "Join Our Team", title: "What Could We Build Together?", body: "Let us get to know your expertise. The right person, timing, and project can make the difference.", cta: "Introduce Yourself" },
    offices: { eyebrow: "Global Presence", title: "Two main offices. Five cities. One standard.", body: "Our main offices in Istanbul and New York, supported by our representation in Dubai, Gaziantep, and Paris, create an integrated model that stays close to different markets.", main: "Main Office", representatives: "Representative Offices", directions: "Get Directions", contact: "Direct Contact" },
    work: { eyebrow: "Work With Us", title: "You Set the Goal. We Build the Way.", body: "From market entry and brand launches to growth strategy, technology, and operational infrastructure, we turn your ambition into a sustainable, measurable, and scalable system.", switch: "Looking to join our team?", formEyebrow: "Tell Us About Your Project", formTitle: "Let’s plan your next stage of growth.", formBody: "A new market, product launch, sub-brand, marketing operation, digital product, or software project—share your goal and the scope you need, and we will identify the right place to begin.", submit: "Send Your Project", success: "Your project has reached our team. We will review the details and get in touch with you." },
    careers: { eyebrow: "Careers & Opportunities", title: "Let’s meet before there is an opening.", body: "We may not always have an open position. But we do not wait for a vacancy to meet the right people. Share your expertise, and we will remember you when the right project comes along.", switch: "Want to discuss a project?", networkLabel: "Sellf Talent Network", networkTitle: "Good work happens when the right people come together.", networkBody: "Sellf projects grow through specialists from different disciplines. If you work freelance, periodically, or project by project, we would like to know you, your approach, and your work.", modesTitle: "We come together around what the project needs.", modesBody: "We collaborate through freelance, periodic, project-based, and long-term models. This is not an active job listing or a promise of employment; it is a space to meet for future opportunities.", formLabel: "Introduce Yourself", formTitle: "Show us what you do well.", formBody: "We do not need a long cover letter. Your expertise, approach, and selected work are enough.", submit: "Send My Profile", success: "Your profile has been added to our Talent Network. We will contact you when a relevant project or opportunity comes up." },
    fields: { name: "Full Name", email: "Email", workEmail: "Work Email", phone: "Phone (optional)", company: "Company / Brand", website: "Website (optional)", goal: "What goal would you like to work on?", brief: "Tell us briefly about your project, goals, and the scope you need.", start: "When would you like to begin?", budget: "Approximate budget range (optional)", location: "City / Country", expertise: "Area of expertise", portfolio: "Portfolio / Website", linkedin: "LinkedIn (optional)", model: "Preferred working model", availability: "Availability", intro: "Tell us briefly about yourself and how you work.", cv: "CV (optional, PDF/DOC/DOCX — max 5 MB)", error: "Something went wrong. Please try again or email team@sellfmedia.com.", sending: "Sending…" }
  }
} as const;

export const goals = {
  tr: ["Büyüme Stratejisi", "Yeni Pazara Giriş", "Ürün veya Marka Lansmanı", "Pazarlama ve Performans", "Marka ve Konumlandırma", "Web, Dijital Ürün veya Yazılım", "Operasyon ve Otomasyon", "Araştırma ve Analiz", "Henüz Netleştirmedik"],
  en: ["Growth Strategy", "New Market Entry", "Product or Brand Launch", "Marketing and Performance", "Brand and Positioning", "Web, Digital Product, or Software", "Operations and Automation", "Research and Analysis", "Not Defined Yet"]
} as const;

export const expertise = {
  tr: ["Tasarım ve yaratıcı üretim", "Video, motion ve prodüksiyon", "Sosyal medya ve içerik", "Performans pazarlaması", "Yazılım ve no-code geliştirme", "Strateji, araştırma ve danışmanlık"],
  en: ["Design and creative production", "Video, motion, and production", "Social media and content", "Performance marketing", "Software and no-code development", "Strategy, research, and consulting"]
} as const;

export const workModes = ["Freelance", "Project-based", "Periodic", "Remote", "Hybrid", "Long-term collaboration"] as const;
