import type {EngageToolKey} from './analytics'

type ReportValue = unknown

export type DownloadableReport = {
  tool: EngageToolKey
  language: 'tr' | 'en'
  title: string
  input: Record<string, ReportValue>
  result: Record<string, ReportValue>
}

export function escapeHtml(value: unknown) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;')
}

function humanize(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replaceAll('_', ' ')
    .replaceAll('-', ' ')
    .replace(/^./, (letter) => letter.toUpperCase())
}

function renderValue(value: ReportValue): string {
  if (value === null || value === undefined || value === '') return '<span class="muted">—</span>'
  if (typeof value === 'boolean') return value ? 'Evet / Yes' : 'Hayır / No'
  if (typeof value !== 'object') return escapeHtml(value)
  if (Array.isArray(value)) {
    if (!value.length) return '<span class="muted">—</span>'
    return `<ul>${value.map((item) => `<li>${renderValue(item)}</li>`).join('')}</ul>`
  }
  return `<dl>${Object.entries(value as Record<string, unknown>).map(([key, item]) => `<div><dt>${escapeHtml(humanize(key))}</dt><dd>${renderValue(item)}</dd></div>`).join('')}</dl>`
}

export function createReportHtml(report: DownloadableReport, recipient: {fullName: string; companyName: string}) {
  const isTr = report.language === 'tr'
  const generated = new Intl.DateTimeFormat(isTr ? 'tr-TR' : 'en-US', {dateStyle: 'long', timeStyle: 'short'}).format(new Date())
  return `<!doctype html><html lang="${report.language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(report.title)}</title><style>
  :root{color-scheme:light;font-family:Inter,Arial,sans-serif;color:#11131a;background:#f3f4f8}body{margin:0;padding:40px}main{max-width:900px;margin:auto;background:#fff;border:1px solid #e3e5ec;border-radius:24px;overflow:hidden}.head{padding:36px 42px;background:#101117;color:#fff}.brand{font-size:12px;letter-spacing:.2em;color:#aeb2ff}.head h1{font-size:32px;margin:18px 0 10px}.head p{margin:4px 0;color:#c9cad3}.content{padding:34px 42px}section{margin:0 0 34px}h2{font-size:13px;letter-spacing:.12em;text-transform:uppercase;color:#555cff;border-bottom:1px solid #e8e9ef;padding-bottom:12px}dl{margin:0}dl div{display:grid;grid-template-columns:minmax(150px,35%) 1fr;gap:18px;padding:10px 0;border-bottom:1px solid #f0f1f4}dt{font-weight:600;color:#535661}dd{margin:0;overflow-wrap:anywhere}dd dl{padding-left:10px}ul{margin:0;padding-left:20px}.muted{color:#9295a0}.foot{padding:22px 42px;background:#f7f7fa;color:#777b86;font-size:12px}@media print{body{padding:0;background:#fff}main{border:0;border-radius:0}.head{-webkit-print-color-adjust:exact;print-color-adjust:exact}}@media(max-width:640px){body{padding:0}main{border-radius:0}.head,.content,.foot{padding:26px 22px}dl div{grid-template-columns:1fr;gap:5px}}
  </style></head><body><main><header class="head"><span class="brand">SELLF ENGAGE</span><h1>${escapeHtml(report.title)}</h1><p>${escapeHtml(recipient.companyName)} · ${escapeHtml(recipient.fullName)}</p><p>${escapeHtml(generated)}</p></header><div class="content"><section><h2>${isTr ? 'Analiz girdileri' : 'Analysis inputs'}</h2>${renderValue(report.input)}</section><section><h2>${isTr ? 'Analiz sonucu' : 'Analysis result'}</h2>${renderValue(report.result)}</section></div><footer class="foot">${isTr ? 'Bu rapor Sellf Engage aracı tarafından sağlanan girdiler üzerinden oluşturulmuştur.' : 'This report was generated by a Sellf Engage tool from the supplied inputs.'}</footer></main></body></html>`
}

export function reportFileName(tool: EngageToolKey, companyName: string) {
  const company = companyName.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48) || 'report'
  return `sellf-${tool}-${company}.html`
}
